data:
  HAM10000:
    root_path: ''
    img_path: ''
    train_csv: ''
    val_csv: ''
    test_csv: ''

  fitzpatrick: ''
    root_path: ''
    img_path: ''
    train_csv: ''
    val_csv: ''
    test_csv: ''

  papila:
    root_path: ''
    img_path: ''
    train_csv: ''
    val_csv: ''
    test_csv: ''

  ol3i:
    root_path: ''
    img_path: ''
    train_csv: ''
    val_csv: ''
    test_csv: ''
    
  oasis:
    root_path: ''
    img_path: ''
    train_csv: ''
    val_csv: ''
    test_csv: ''

  chexpert:
    root_path: ''
    img_path: ''
    train_csv: ''
    val_csv: ''
    test_csv: ''

  glaucoma:
    root_path: ''
    img_path: ''
    train_csv: ''
    val_csv: ''
    test_csv: ''

  

  